apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: default-allow-privilege-escalation
  labels:
    app.kubernetes.io/name: default-allow-privilege-escalation-webhook
    app.kubernetes.io/instance: default-allow-privilege-escalation
data:
  config.yaml: |
    server:
      tls:
        enabled: true
