apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook
  namespace: default-allow-privilege-escalation
  # labels: {} # managed by kustomize
data:
  config.yaml: |
    server:
      tls:
        enabled: true
    app:
      default: false
