apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- namespace.yaml
- service-account.yaml
- service.yaml
