apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: default-allow-privilege-escalation
  # labels: {} # managed by kustomize
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  # selector: {} # managed by kustomize
