apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: default-allow-privilege-escalation
  labels:
    app.kubernetes.io/name: default-allow-privilege-escalation-webhook
    app.kubernetes.io/instance: default-allow-privilege-escalation
